### ISSUE TITLE
option to disable tobii mouse smoothing

### ISSUE THREAD

**Issue by farzher** [EsotericSoftware/clippy#10]
why does the mouse move over time to where i'm looking instead of instantly teleporting?

when i press tobiiClickHotkey and then try to quickly correct it with my mouse, my mouse movement cancels it midway. i have to press the button, then wait, then i can correct it. which is dumb. i'm trying to use this to improve my mouse speed!

either add the option to make it instantly warp (like it does with the default tobii software). or make this the default/only option

**Comment by NathanSweet** [comment]
You may try being more polite when requesting free work from others on the software that was provided to you for free.

The mouse moves over time to reduce disorientation. Also at the very bottom of the screen the mouse cannot be seen at all, so with an instant teleport to that position it is not obvious where the mouse is. I agree the animation time could be configurable, where zero would be instant.

**Comment by NathanSweet** [comment]
Latest release still animates when the click hotkey is held, but when the hotkey is released, the mouse is instantly moved to the gaze position and the click is done there. This way the animation never gets cancelled halfway and doesn't interfere with a fast click.
