### ISSUE TITLE
Offer a release without JRE required?

### ISSUE THREAD

**Issue by nash8350** [EsotericSoftware/clippy#11]
Hi I would like to try running clippy but I don't want to install Java on my system because of security issues and it constantly needs to be updated.  Would you be willing to offer an executable release for Windows that does not require a JRE? Maybe this would make it easier for more people to use?

To do this, you could use one of the many executable wrappers such as launch4j https://sourceforge.net/projects/launch4j. It just bundles any needed dependencies into a single exe file.

**Comment by NathanSweet** [comment]
A JRE is always required to run any Java application. I'm not excited about bundling a JRE with Clippy, as it makes the app much larger and is inconvenient for me. You can get a portable JRE with no installer / update crap here:
https://portableapps.com/apps/utilities/java_portable
