### ISSUE TITLE
Example configuration file

### ISSUE THREAD

**Issue by nash8350** [EsotericSoftware/clippy#12]
Hi can you please provide an example configuration file? I'm a little confused because the readme says the file should be named config.json. However, the code seems to think it's data.json? Also, what is the allowed format for this file? I tried creating one for enabling Tobii but it did not seem to work.

**Comment by NathanSweet** [comment]
Clippy creates a config.json file if one doesn't exist. So, delete any config.json file you have, run Clippy, see it created a config.json, edit the config.json, restart Clippy to see your config changes. The file is a modified JSON format where quotes are optional. It will accept JSON if that is easier for you.

data.json contains values that Clippy writes to keep track of things. You don't normally need to edit data.json.
