### ISSUE TITLE
Not an Issue but, WE NEED AN...

### ISSUE THREAD

**Issue by superseani2** [EsotericSoftware/clippy#14]
WE NEED an option in config.json to NOT click. I perssonaly dont see why we shouldn't have the option to NOT CLICK. 
-tobiiClickAfterHotkey : True/False

WHY?! :grinning: 
-Because I rather click myself
-I ALWAYS miss Click.

When i bind my EXTRA-mouse button on my Logitech Mouse or Autoit, i'd rather tell the button to click afterward, Which give MORE CONTROL  over all. 

In either Logitech or RAZER software... EVEN this chiness keyboard i have (40$ amazon) HAS an software to ADD keys ,create macros and even WAIT for the key to stop beeing pressed before performing Further actions/another macro.
.
So all thats left to do to make this at least 1% Better, is adding the option to ; 
tobiiClickAfterHotkey : True/False

i would really do it myself, but i have -% knowledge in Json.

**Comment by NathanSweet** [comment]
That's a lot of caps. What are you talking about? Eye tracking?
