### ISSUE TITLE
Many thanks!

### ISSUE THREAD

**Issue by torrent99** [EsotericSoftware/clippy#15]
Not An issue but thanks instead.

 I use  clippy everyday together with the tobii  eye tracker to replace my mouse which is very painful to use.
 So many thanks indeed!
 cheers
 Steve

**Comment by NathanSweet** [comment]
Thanks Steve! I'm glad you find it useful. :)

BTW, I highly suggest a Kensington Expert Mouse, which is actually a trackball. It has a scroll ring, which is great, and the trackball is very large so easy to use with fingertips. I don't suggest using the wrist rest that comes with it though. I also use a 3m AKT60LE keyboard tray.

**Comment by torrent99** [comment]
Thanks Nathan. I'm afraid I've gone beyond trackballs (I have 3 fully
restored Microsoft trackball Explorer  1.0 trackballs, and numerous other
pointing  devices!)

I've added, a configurable fixed eye tracking offset to Clippy as it was
always getting the initial position t too eye. mouse. My next alterations
will be either to add some key press zones outside of the monitor, or a
bigger project to use Clippy together with a teensy device to turn my
laptop into a giant eye powered mouse. (getting the Tobii to work natively
on the PCs at work would be next to impossible)

Cheers

Steve
