### ISSUE TITLE
Tobii head tracking not working

### ISSUE THREAD

**Issue by pepper1958** [EsotericSoftware/clippy#16]
Just loaded clippy, Caps Lock hot key works to move curser, but moving head does not move curser when holding hot key down.

Any suggestions to fix?

**Comment by NathanSweet** [comment]
What hardware are you using? Clippy is using the [eye event](https://github.com/EsotericSoftware/clippy/blob/master/jni/com.esotericsoftware.clippy.tobii.EyeX.c#L144) provided by the Tobii drivers. If that doesn't give eye events, Clippy won't do head position tracking (which is actually the position of the [left eye](https://github.com/EsotericSoftware/clippy/blob/master/src/com/esotericsoftware/clippy/Tobii.java#L117)).

**Comment by pepper1958** [comment]
I'm using Tobii 4C.

**Comment by pepper1958** [comment]
Should left eye

storeHeadAdjustment = false; 

be set to true?

**Comment by NathanSweet** [comment]
I also have a 4C. It should work fine as-is. What driver version are you using? I have 2.13.3. `storeHeadAdjustment` is unrelated. If you are Java-savvy you could try debugging it, otherwise I'm not sure what to say since it is working for me (and others).

**Comment by pepper1958** [comment]
Thanks, its working now.

**Comment by NathanSweet** [comment]
What changed so others with a similar problem can solve it?
