### ISSUE TITLE
Using Tobii to track idle and lock the PC

### ISSUE THREAD

**Issue by stawari** [EsotericSoftware/clippy#17]
Hi NathanSweet,
First thing, My name is Ken, I know this through finding Tobii improve apps, and this one is really great, now I can use mouseless a lot of thing, I was think I couldn't do it before. This app is very great when using with my autohotkey mapping + tobii. 
Many thanks about this.
And just still one think I'm looking for to using Tobii that is quick lock on Windown 10, The idea is when you not sit at your front of your PC, it will auto lock. and come back with Windown Hellow. There is a function is Dynamic Lock, but it's not really stable. 
So with Tobii my idea is we can check the data from it to know if we have font of monitor, and if after 30s it's can get the data, It will lock the PC.
Is this idea can update to Clippy if yes this is so great thing.
Thanks.
Ken

**Comment by NathanSweet** [comment]
Hi Ken, sorry it took so long but I finally got around to adding it. In the config set `autoLockSeconds`. The timeout is reset if any key is pressed or the mouse is moved or if Tobii sees your eyes. This way it works even without a Tobii.
