### ISSUE TITLE
Tobii eye tracking to access the Windows taskbar

### ISSUE THREAD

**Issue by MinxiesDev** [EsotericSoftware/clippy#18]
Absolutely love this project.

Specifically the Tobii eye tracking feature.

Would it be possible to access the windows taskbar using this?

Happy to run custom task bar, if that would help?

I noticed it can reach the taskbar if it's docked on the left or the right side of the screen.

OS: Windows 10 64bit.

**Comment by NathanSweet** [comment]
Hello! Not sure what you mean. I can look at my windows taskbar and click to select an application. I use the taskbar at the bottom of the screen.

**Comment by MinxiesDev** [comment]
Ahh, interesting. So it may be an issue with my local setup?

I have a 1200x1080 monitor, single screen.

It's working beutifully on the side, so I'm happy, but it might be nice for the project.

Interestingly, when I resize the taskbar at the bottom, I can access the newly added area.

I'm using small taskbar icons. When I resize to using regular sized icons, I can, as above, only access the newly added area.

So it's like there's a fixed 30px area at the bottom (size of my taskbar with small icons) that is inaccessable (even when the taskbar is docked to the left). This problem persists after restarting Clippy.

**Comment by MinxiesDev** [comment]
Having a further play, it looks like there's a 15px inacessable area at the top as well. This hasn't caused any issues so far, so I haven't noticed until just now.

**Comment by MinxiesDev** [comment]
Another update, there is now inacessable bars (15px each?) to the left and right of the screen. I don't recall this being there in the past. These may have been introduced by redocking the taskbar to the right.

Either way, I think Clippy may be caching the screen size too small?

**Comment by NathanSweet** [comment]
Clippy uses margins to keep the mouse on the screen:
https://github.com/EsotericSoftware/clippy/blob/master/src/com/esotericsoftware/clippy/Tobii.java#L18
To change these, you would need to change the source and recompile Clippy.

**Comment by MinxiesDev** [comment]
Aah, handy to know.

Thanks, I don't think I'll go though the trouble of compiling it just yet. Might be nice if this was exposed for config variables if you think this is important. It seems to break the usage if you don't have any OS resolution scaling of any kind?

Best Regards,
James
