### ISSUE TITLE
Option to change the font / special characters

### ISSUE THREAD

**Issue by ENMAGames** [EsotericSoftware/clippy#2]
Using special and/or asian characters, works, however in the preview list the show up as question marks, because the glphs dont exist in the font used. Could there be a way to change the font or could Clippy use a font that has like most characters?

**Comment by NathanSweet** [comment]
You can set the font in the config file. The default is `Consolas-14`. The format is on of:

```
fontname-style-pointsize 
fontname-pointsize 
fontname-style 
fontname 
fontname style pointsize 
fontname pointsize 
fontname style 
fontname 
```

`style` is one of the four case-insensitive strings: "PLAIN", "BOLD", "BOLDITALIC", or "ITALIC", and pointsize is a positive decimal integer representation of the point size. For example, if you want a font that is Arial, bold, with a point size of 18, you would use "Arial-BOLD-18".

**Comment by ENMAGames** [comment]
Ah yes of course. Beautiful. :D
