### ISSUE TITLE
Tobii eye tracker right click feature

### ISSUE THREAD

**Issue by MinxiesDev** [EsotericSoftware/clippy#20]
I use the Tobii eye tracker feature a LOT! This is a huge boon for sufferers of RSI. There's nothing else quite like it on the market (that I know of).

I wonder if you've thought about a right click feature?

So, if you hold down capslock, it's right click but you hold down another key for right click.

I'm thinking about hacking it with autohotkey but wondered if anyone here had any better ideas?

**Comment by stawari** [comment]
I did some hack to comebine clippy with autohotkey, I can use it to select text, actualy clippy have drag hotkey but not so good like I want, So a little help from autohotkey, it work perfect now,I think autohotkey is the best to make it work more perfect now.

**Comment by MinxiesDev** [comment]
Cool, well to make this easier if we have multiple tobii hotkeys. This way
we can map them to different things in autohotkey. So instead of clicking
after a hotkey release perhaps it would be best that we are given the
option of a configurable another configurable key (with the default being a
click, if this parameter isn't set).

So my setup would be as follows

Capslock -> click
Numpad 1 -> [special keyboard key]

The special keyboard key can then be mapped in AHK for whatever
