### ISSUE TITLE
Exclusive head tracking key

### ISSUE THREAD

**Issue by Gazareth** [EsotericSoftware/clippy#23]
Would it be possible to get a key/modifier/setting to enable mouse movement that doesn't follow your eyes but is just moved by your head?

The main reason I want this is down to a script called [DragToScroll](https://www.autohotkey.com/boards/viewtopic.php?t=38457) which I use to scroll the page by moving my mouse up and down. What would be cool is if I could scroll the page by moving my head, whilst my eyes are elsewhere reading other things on the page.

I've tried to poke around and get something like this done on my fork, but I am having a lot of difficult just separating the head movement routine from the eye gaze routine. Even just some advice on how it might be achieved so I could do it in my own version would be appreciated.

**Comment by NathanSweet** [comment]
Huh, seems a little odd. You very quickly run out of space with head movement. Arrow down/up can scroll. FWIW, personally I use a Kensington Expert Mouse (that's the name but actually it is a trackball), which has a scroll wheel around the ball. It's fantastic!

If you want to do it though, delete these lines in `setMouseToGaze`:
```
gazeSnappedX = x;
gazeSnappedY = y;

setMousePosition(x, y, true);
```
And replace them with:
```
getMouse(mouse);
gazeSnappedX = mouse.x;
gazeSnappedY = mouse.y;
mouseLastX = mouse.x;
mouseLastY = mouse.y;
mouseStartX = mouse.x;
mouseStartY = mouse.y;
mouseEndX = mouse.x;
mouseEndY = mouse.y;
mouseMoveTime = 0;
```
