### ISSUE TITLE
Clippy eye tracking intermittent 

### ISSUE THREAD

**Issue by MinxiesDev** [EsotericSoftware/clippy#24]
Very happy with the way Clippy eye tracking performs but at times it seems to stop tracking. I know it is built in such a way that it stops tracking when you move the mouse but I am not doing this. I wonder if this is a known issue?

I’m using a Tobii 4C on Windows 10.

**Comment by NathanSweet** [comment]
I haven't noticed it. Can you reproduce it consistently? Could it be the Tobii loses tracking briefly? Glasses, reflections, lighting, etc can influence the Tobii.

**Comment by MinxiesDev** [comment]
Thanks for the quick reply.

I wonder if losing tracking cause this issue. However, having tested closing my eyes either one or both, Clippy seems to keep tracking once it finds my eyes again. So I figured it couldn’t be the loss of tracking. I'm of course holding down the hotkey (capslock) and nothing else is intercepting it.


My Java version is: 

C:\Users\james>java --version
java 12.0.1 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)


I wish I could provide more of a diagnostic but it does seem to be intermittent. It looses tracking anywhere within a period of 2-10 seconds of use (and never clicks). It could be noise introduced by one of my mice? (Though the cursor doesn't move at all). I'm wondering if commenting out that section of code may help, just to diagnose? Thereafter I may add a filter to filter out miniscule values. This seems unlikely but I'm just grasping at straws at this stage. Love this software.

**Comment by NathanSweet** [comment]
Tobii can lose tracking at any time, eg you close your eyes or look away from it. Do you have the two little eyes on the Tobii icon in the system tray when Clippy stops moving the mouse/clicking? If those eyes are gone, Tobii lost tracking.

Does recalibrating the Tobii help?

Oh, you think small mouse movements are disabling tracking? That could be. Could require the mouse to be moved some number of pixels, maybe within a time period, before disabling Clippy's tracking.

**Comment by MinxiesDev** [comment]
Got to the bottom of it. Turns out my keyboard switch actuation it's faulty and was sending release and press commands if the key is not held down hard enough!!!

FWIW, I was using a Microsoft sculpt keyboard (Thanks Microsoft!)

Very sorry for the false alarm. As a programmer myself, I know how annoying this can be!!

Best,
James
