### ISSUE TITLE
Keyboard shortcuts does not work on Mac

### ISSUE THREAD

**Issue by junhe** [EsotericSoftware/clippy#28]
```
1. snipet A
2. snipet B
3. snipet C
4. snipet D
```

I suppose that when a list like this is shown, we should be able to use keyboard to select the item. For example, press UP/DOWN key to select; or press key '2' to paste snippet B. But when I do that on my Mac, nothing happens. 

System:
- macOS Big Sur, Version 11.2.1
- Clipy: v1.2.1

**Comment by NathanSweet** [comment]
Many pars of Clippy are specific to Windows. I'm afraid it would be a lot of work to support Mac and I'm not a Mac user myself.
