### ISSUE TITLE
How to dismiss break dialogue?

### ISSUE THREAD

**Issue by searchy2** [EsotericSoftware/clippy#7]
My current understanding is that the computer must be inactive for the amount of time set in configs for the break dialogue to automatically be disabled. is that the case? Is there a hotkey to manually disable the break timer? Thanks for your great work on Clippy!

**Comment by NathanSweet** [comment]
Set `toggleHotkey` to disable both gamma and break warnings. There isn't a hotkey to reset the break warning, else I would use it and defeat the whole purpose. ;) It's supposed to be annoying. You can just close Clippy and immediately start it again, but that is cheating! Set `breakWarningMinutes` to 0 to disable it completely.

**Comment by searchy2** [comment]
So the break dialogue can only be dismissed if mouse and keyboard are inactive for 5 minutes?

**Comment by NathanSweet** [comment]
Be inactive for `X` minutes, or press the `toggleHotkey`, or restart Clippy. The idea is that you have to take a break to dismiss the break warning dialog.
